@startuml ActiviteMaintenance
title Diagramme d'activité — Gestion de la maintenance (aligné UML)
skinparam shadowing false
skinparam ArrowColor DarkSlateGray
skinparam activity {
  BorderColor DarkSlateGray
  BackgroundColor White
  DiamondBorderColor DarkSlateGray
  DiamondBackgroundColor LightYellow
  StartColor DarkGreen
  EndColor FireBrick
  BarColor DarkSlateGray
}

|#D4EFDF|Technicien|
start
:Détecter une panne (équipement défectueux);
:Signaler une DemandeMaintenance;

|#E5E8E8|Système|
:Enregistrer la DemandeMaintenance;

|#FCF3CF|ChefDeQuart|
:Consulter la DemandeMaintenance;
if (Demande valide ?) then (oui)
  :Valider la DemandeMaintenance;

  |#E5E8E8|Système|
  :Créer une ou plusieurs Interventions;
  :Notifier le technicien demandeur;

  |#D4EFDF|Technicien|
  :Recevoir la validation de réparation;
  :Réparer l'équipement (Intervention);

  while (Panne résolue ?) is (non)
    |#E5E8E8|Système|
    :Alerter le chef de quart;
    |#FCF3CF|ChefDeQuart|
    :Affecter un autre technicien;
    |#D4EFDF|Technicien|
    :Recevoir l'affectation;
    :Réparer l'équipement (Intervention);
  endwhile (oui)

  |#D4EFDF|Technicien|
  :Mettre à jour l'équipement;
  |#E5E8E8|Système|
  :Clôturer la DemandeMaintenance;
else (non)
  |#FCF3CF|ChefDeQuart|
  :Rejeter la DemandeMaintenance;
endif
stop
@enduml